package surveiCovid19.component;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import surveiCovid19.Database;
import surveiCovid19.MainFrame;
import surveiCovid19.blokC;
import javax.swing.JScrollPane;
import surveiCovid19.blokA;

public class editDataBlokC extends javax.swing.JPanel {
    private final JScrollPane contentScrollPane;
    private int idPerusahaan;
    /**
     * Creates new form entryPanel
     */
    CardLayout cardLayout;
    public editDataBlokC(JScrollPane contentScrollPane, int idPerusahaan) throws SQLException {
        this.contentScrollPane = contentScrollPane;
        initComponents();
        this.idPerusahaan = idPerusahaan;
        idPerusahaan_txt.setEnabled(false);
        insertInfo();
    }
    
    private void clearForm() { 
        idPerusahaan_txt.setText("");
        Kondisi.setSelectedIndex(-1); // Mengosongkan pilihan dropdown
        Penurunan.setSelectedIndex(-1); // Mengosongkan pilihan dropdown
        PenurunanLanjutan.setText("");
        Peningkatan.setSelectedIndex(-1); // Mengosongkan pilihan dropdown
        PeningkatanLanjutan.setText("");
        Upaya.setSelectedIndex(-1); // Mengosongkan pilihan dropdown
    }

    
    public void insertInfo() throws SQLException {
        String sql = "SELECT * FROM bloka WHERE id_perusahaan = ?";
        String sql2 = "SELECT * FROM blokc WHERE id_perusahaan = ?";

        try (Connection conn = Database.getInstance().getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             PreparedStatement pst2 = conn.prepareStatement(sql2)) {

            pst.setInt(1, idPerusahaan);
            pst2.setInt(1, idPerusahaan);

            try (ResultSet rs = pst.executeQuery();
                 ResultSet rs2 = pst2.executeQuery()) {
                
                if (rs2.next()) {
                    idPerusahaan_txt.setText(rs2.getString("id_perusahaan"));
                    Kondisi.setSelectedItem(rs2.getString("income_Sblm_Covid"));
                    Penurunan.setSelectedItem(rs2.getString("penurunan"));
                    PenurunanLanjutan.setText(rs2.getString("penurunan_lain"));
                    Peningkatan.setSelectedItem(rs2.getString("peningkatan"));
                    PeningkatanLanjutan.setText(rs2.getString("peningkatan_lain"));
                    Upaya.setSelectedItem(rs2.getString("upaya_peningkatan"));
                }
            }
        } catch (SQLException e) {
            throw e;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTanamanPangan = new javax.swing.ButtonGroup();
        buttonGroupHortikultura = new javax.swing.ButtonGroup();
        buttonGroupPeternakan = new javax.swing.ButtonGroup();
        buttonGroupKehutanan = new javax.swing.ButtonGroup();
        buttonGroupPerikanan = new javax.swing.ButtonGroup();
        buttonGroupKunjungan = new javax.swing.ButtonGroup();
        contentScrollPanel = new javax.swing.JScrollPane();
        pnlEntry = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PenurunanLanjutan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kirimButton = new javax.swing.JButton();
        inputDataLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Kondisi = new javax.swing.JComboBox<>();
        Penurunan = new javax.swing.JComboBox<>();
        Peningkatan = new javax.swing.JComboBox<>();
        PeningkatanLanjutan = new javax.swing.JTextField();
        Upaya = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        idPerusahaan_txt = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(206, 214, 224));

        contentScrollPanel.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kondisi Pendapatan Usaha Dibanding Sebelum Covid-19");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Penurunan Pendapatan Usaha Akibat Covid-19");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Besaran Spesifik Persentase Penurunan Pendapatan Usaha Akibat Covid-19");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Besaran Spesifik Persentase Peningkatan Pendapatan Usaha Covid-19");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Upaya Meningkatkan Pendapatan Usaha");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Peningkatan Pendapatan Usaha Akibat Covid-19");

        kirimButton.setBackground(new java.awt.Color(81, 137, 198));
        kirimButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kirimButton.setForeground(new java.awt.Color(255, 255, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        inputDataLabel.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        inputDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputDataLabel.setText("EDIT DATA");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setText("BLOK C. DAMPAK TERHADAP KINERJA FINANSIAL");

        Kondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menurun", "Tetap", "Meningkat" }));

        Penurunan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<= 20%", "21 - 40%", "41 - 60%", "61 - 80%", "81 - 100%" }));

        Peningkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<= 20%", "21 - 40%", "41 - 60%", "61 - 80%", "81 - 100%", "> 100%" }));

        Upaya.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penambahan modal kerja", "Penambahan tenaga kerja", "Peningkatan teknologi", "Kapasitas produksi meningkat" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID Perusahaan");

        idPerusahaan_txt.setEditable(false);
        idPerusahaan_txt.setAutoscrolls(false);

        hapus.setBackground(new java.awt.Color(81, 137, 198));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputDataLabel)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Peningkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Penurunan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PenurunanLanjutan)
                                .addComponent(PeningkatanLanjutan)
                                .addComponent(Upaya, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Kondisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idPerusahaan_txt, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(inputDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(idPerusahaan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Penurunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PenurunanLanjutan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Peningkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(PeningkatanLanjutan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Upaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kirimButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout pnlEntryLayout = new javax.swing.GroupLayout(pnlEntry);
        pnlEntry.setLayout(pnlEntryLayout);
        pnlEntryLayout.setHorizontalGroup(
            pnlEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntryLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        pnlEntryLayout.setVerticalGroup(
            pnlEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntryLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        contentScrollPanel.setViewportView(pnlEntry);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        blokC blokC = new blokC();
        blokC.setIdPerusahaan(Integer.parseInt(idPerusahaan_txt.getText()));
        blokC.setIncomeSblmCovid((String)Kondisi.getSelectedItem());
        blokC.setPenurunan((String) Penurunan.getSelectedItem());
        blokC.setPenurunanLain(PenurunanLanjutan.getText());
        blokC.setPeningkatan((String) Peningkatan.getSelectedItem());
        blokC.setPeningkatanLain(PeningkatanLanjutan.getText());
        blokC.setUpayaPeningkatan((String) Upaya.getSelectedItem());

        try {
            Database.getInstance().updateBlokC(blokC);
            JOptionPane.showMessageDialog(this, "Data Berhasil Diedit");
            contentScrollPane.setViewportView(new viewPanel(contentScrollPane, idPerusahaan));
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Lengkapi Semua Data", "Data Gagal Tersimpan", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        // Konfirmasi penghapusan data
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Panggil method deleteBlokA dari kelas Database
                Database.getInstance().deleteBlokC(idPerusahaan);
                JOptionPane.showMessageDialog(this, "Data successfully deleted.");
                clearForm();
            } catch (SQLException ex) {
                Logger.getLogger(editDataBlokA.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to delete data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Kondisi;
    private javax.swing.JComboBox<String> Peningkatan;
    private javax.swing.JTextField PeningkatanLanjutan;
    private javax.swing.JComboBox<String> Penurunan;
    private javax.swing.JTextField PenurunanLanjutan;
    private javax.swing.JComboBox<String> Upaya;
    private javax.swing.ButtonGroup buttonGroupHortikultura;
    private javax.swing.ButtonGroup buttonGroupKehutanan;
    private javax.swing.ButtonGroup buttonGroupKunjungan;
    private javax.swing.ButtonGroup buttonGroupPerikanan;
    private javax.swing.ButtonGroup buttonGroupPeternakan;
    private javax.swing.ButtonGroup buttonGroupTanamanPangan;
    private javax.swing.JScrollPane contentScrollPanel;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idPerusahaan_txt;
    private javax.swing.JLabel inputDataLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kirimButton;
    private javax.swing.JPanel pnlEntry;
    // End of variables declaration//GEN-END:variables
}
