/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package surveiCovid19;

import surveiCovid19.component.HomePanel;
import surveiCovid19.component.dataPanelBlokC;
import surveiCovid19.component.entryDataBlokA;
import surveiCovid19.component.entryDataBlokC;
import surveiCovid19.component.dataPanelBlokA;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    CardLayout cardLayout;
    public MainFrame() {
        setTitle("TANGGUH");
        initComponents();
        contentScrollPane.setViewportView(new HomePanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentScrollPane = new javax.swing.JScrollPane();
        homePanel1 = new surveiCovid19.component.HomePanel();
        navigationPanel = new javax.swing.JPanel();
        inputDataBlokA = new javax.swing.JButton();
        lihatDataBlokA = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        inputDataBlokC = new javax.swing.JButton();
        lihatDataBlokC = new javax.swing.JButton();
        lihatDataTitle = new javax.swing.JButton();
        inputDataTitle = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N

        contentScrollPane.setBorder(null);
        contentScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        contentScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        contentScrollPane.setHorizontalScrollBar(null);
        contentScrollPane.setMaximumSize(new java.awt.Dimension(936, 621));
        contentScrollPane.setViewportView(homePanel1);

        navigationPanel.setBackground(new java.awt.Color(4, 84, 151));
        navigationPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        navigationPanel.setMinimumSize(new java.awt.Dimension(200, 0));
        navigationPanel.setPreferredSize(new java.awt.Dimension(200, 648));

        inputDataBlokA.setBackground(new java.awt.Color(5, 69, 105));
        inputDataBlokA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputDataBlokA.setForeground(new java.awt.Color(244, 242, 242));
        inputDataBlokA.setText("Data Blok A");
        inputDataBlokA.setBorderPainted(false);
        inputDataBlokA.setContentAreaFilled(false);
        inputDataBlokA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputDataBlokA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputDataBlokA.setMargin(new java.awt.Insets(0, 38, 0, 0));
        inputDataBlokA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputDataBlokAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputDataBlokAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputDataBlokAMouseExited(evt);
            }
        });
        inputDataBlokA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataBlokAActionPerformed(evt);
            }
        });

        lihatDataBlokA.setBackground(new java.awt.Color(5, 69, 105));
        lihatDataBlokA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lihatDataBlokA.setForeground(new java.awt.Color(244, 242, 242));
        lihatDataBlokA.setText("Data Blok A");
        lihatDataBlokA.setBorderPainted(false);
        lihatDataBlokA.setContentAreaFilled(false);
        lihatDataBlokA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatDataBlokA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lihatDataBlokA.setMargin(new java.awt.Insets(0, 38, 0, 0));
        lihatDataBlokA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lihatDataBlokAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lihatDataBlokAMouseExited(evt);
            }
        });
        lihatDataBlokA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataBlokAActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(5, 69, 105));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(244, 242, 242));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        inputDataBlokC.setBackground(new java.awt.Color(5, 69, 105));
        inputDataBlokC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputDataBlokC.setForeground(new java.awt.Color(244, 242, 242));
        inputDataBlokC.setText("Data Blok C");
        inputDataBlokC.setBorderPainted(false);
        inputDataBlokC.setContentAreaFilled(false);
        inputDataBlokC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputDataBlokC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputDataBlokC.setMargin(new java.awt.Insets(0, 38, 0, 0));
        inputDataBlokC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputDataBlokCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputDataBlokCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputDataBlokCMouseExited(evt);
            }
        });
        inputDataBlokC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataBlokCActionPerformed(evt);
            }
        });

        lihatDataBlokC.setBackground(new java.awt.Color(5, 69, 105));
        lihatDataBlokC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lihatDataBlokC.setForeground(new java.awt.Color(244, 242, 242));
        lihatDataBlokC.setText("Data Blok C");
        lihatDataBlokC.setBorderPainted(false);
        lihatDataBlokC.setContentAreaFilled(false);
        lihatDataBlokC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatDataBlokC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lihatDataBlokC.setMargin(new java.awt.Insets(0, 38, 0, 0));
        lihatDataBlokC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lihatDataBlokCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lihatDataBlokCMouseExited(evt);
            }
        });
        lihatDataBlokC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataBlokCActionPerformed(evt);
            }
        });

        lihatDataTitle.setBackground(new java.awt.Color(5, 69, 105));
        lihatDataTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lihatDataTitle.setForeground(new java.awt.Color(244, 242, 242));
        lihatDataTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Asset 6@0.5x.png"))); // NOI18N
        lihatDataTitle.setText("Lihat Data");
        lihatDataTitle.setBorder(null);
        lihatDataTitle.setContentAreaFilled(false);
        lihatDataTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lihatDataTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lihatDataTitle.setIconTextGap(9);
        lihatDataTitle.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lihatDataTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatDataTitleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lihatDataTitleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lihatDataTitleMouseExited(evt);
            }
        });
        lihatDataTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataTitleActionPerformed(evt);
            }
        });

        inputDataTitle.setBackground(new java.awt.Color(5, 69, 105));
        inputDataTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputDataTitle.setForeground(new java.awt.Color(244, 242, 242));
        inputDataTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Asset 5@0.5x.png"))); // NOI18N
        inputDataTitle.setText("Input Data");
        inputDataTitle.setBorder(null);
        inputDataTitle.setContentAreaFilled(false);
        inputDataTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inputDataTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputDataTitle.setIconTextGap(16);
        inputDataTitle.setMargin(new java.awt.Insets(5, 5, 5, 5));
        inputDataTitle.setMaximumSize(new java.awt.Dimension(613, 519));
        inputDataTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputDataTitleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputDataTitleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputDataTitleMouseExited(evt);
            }
        });
        inputDataTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataTitleActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(5, 69, 105));
        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(244, 242, 242));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Asset 2@0.5x.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.setIconTextGap(8);
        homeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        homeButton.setMaximumSize(new java.awt.Dimension(613, 519));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputDataTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputDataBlokA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputDataBlokC, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(lihatDataBlokA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lihatDataTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lihatDataBlokC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDataTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDataBlokA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDataBlokC)
                .addGap(18, 18, 18)
                .addComponent(lihatDataTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lihatDataBlokA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatDataBlokC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
            .addComponent(contentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        JFrame logout = new JFrame("Logout");
        if(JOptionPane.showConfirmDialog(logout, "Semua pekerjaan yang belum tersimpan akan hilang jika anda logout. Apakah anda yakin?","Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        new LoginFrame().setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        logoutButton.setContentAreaFilled(false);
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setContentAreaFilled(true);
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void lihatDataBlokAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataBlokAActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new dataPanelBlokA(contentScrollPane));
    }//GEN-LAST:event_lihatDataBlokAActionPerformed

    private void lihatDataBlokAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataBlokAMouseExited
        // TODO add your handling code here:
        lihatDataBlokA.setContentAreaFilled(false);
    }//GEN-LAST:event_lihatDataBlokAMouseExited

    private void lihatDataBlokAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataBlokAMouseEntered
        // TODO add your handling code here:
        lihatDataBlokA.setContentAreaFilled(true);
    }//GEN-LAST:event_lihatDataBlokAMouseEntered

    private void inputDataBlokAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataBlokAActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new entryDataBlokA());
    }//GEN-LAST:event_inputDataBlokAActionPerformed

    private void inputDataBlokAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokAMouseExited
        // TODO add your handling code here:
        inputDataBlokA.setContentAreaFilled(false);
    }//GEN-LAST:event_inputDataBlokAMouseExited

    private void inputDataBlokAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokAMouseEntered
        // TODO add your handling code here:
        inputDataBlokA.setContentAreaFilled(true);
    }//GEN-LAST:event_inputDataBlokAMouseEntered

    private void inputDataBlokAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokAMouseClicked
        // TODO add your handling code here:
        homeButton.setContentAreaFilled(false);
        inputDataBlokA.setContentAreaFilled(true);
        lihatDataBlokA.setContentAreaFilled(false);
        logoutButton.setContentAreaFilled(false);
    }//GEN-LAST:event_inputDataBlokAMouseClicked

    private void lihatDataTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataTitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatDataTitleMouseClicked

    private void lihatDataTitleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataTitleMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lihatDataTitleMouseEntered

    private void lihatDataTitleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataTitleMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lihatDataTitleMouseExited

    private void lihatDataTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatDataTitleActionPerformed

    private void inputDataTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataTitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataTitleMouseClicked

    private void inputDataTitleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataTitleMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputDataTitleMouseEntered

    private void inputDataTitleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataTitleMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputDataTitleMouseExited

    private void inputDataTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataTitleActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataTitleActionPerformed

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homeButtonMouseClicked

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        // TODO add your handling code here:
        homeButton.setContentAreaFilled(true);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        // TODO add your handling code here:
        homeButton.setContentAreaFilled(false);
    }//GEN-LAST:event_homeButtonMouseExited

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new HomePanel());
    }//GEN-LAST:event_homeButtonActionPerformed

    private void inputDataBlokCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataBlokCActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new entryDataBlokC());
    }//GEN-LAST:event_inputDataBlokCActionPerformed

    private void inputDataBlokCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokCMouseExited
        // TODO add your handling code here:
        inputDataBlokC.setContentAreaFilled(false);
    }//GEN-LAST:event_inputDataBlokCMouseExited

    private void inputDataBlokCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokCMouseEntered
        // TODO add your handling code here:
        inputDataBlokC.setContentAreaFilled(true);
    }//GEN-LAST:event_inputDataBlokCMouseEntered

    private void inputDataBlokCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDataBlokCMouseClicked
        // TODO add your handling code here:
        inputDataBlokC.setContentAreaFilled(true);
    }//GEN-LAST:event_inputDataBlokCMouseClicked

    private void lihatDataBlokCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataBlokCActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new dataPanelBlokC(contentScrollPane));
    }//GEN-LAST:event_lihatDataBlokCActionPerformed

    private void lihatDataBlokCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataBlokCMouseExited
        // TODO add your handling code here:
        lihatDataBlokC.setContentAreaFilled(false);
    }//GEN-LAST:event_lihatDataBlokCMouseExited

    private void lihatDataBlokCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatDataBlokCMouseEntered
        // TODO add your handling code here:
        lihatDataBlokC.setContentAreaFilled(true);
    }//GEN-LAST:event_lihatDataBlokCMouseEntered

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JButton homeButton;
    private surveiCovid19.component.HomePanel homePanel1;
    private javax.swing.JButton inputDataBlokA;
    private javax.swing.JButton inputDataBlokC;
    private javax.swing.JButton inputDataTitle;
    private javax.swing.JButton lihatDataBlokA;
    private javax.swing.JButton lihatDataBlokC;
    private javax.swing.JButton lihatDataTitle;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navigationPanel;
    // End of variables declaration//GEN-END:variables
}
